spring:
  application:
    name: blood-sample-management-api
  mail:
    host: smtp.gmail.com
    port: 587
    username: naiksahil478@gmail.com
    password: suuwwikwwtkfggqo
    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/BloodyEmail?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true

server:
  port: 8081