spring:
  application:
    name: blood-sample-management-api

  datasource:
    username: root
    password: 1234
    url: jdbc:mysql://localhost:3306/bsm_db?createDatabaseIfNotExist=true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql : true

